version: '3'

services:

  broker-services:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart:  always
    ports:
      - "5000:3000"
    deploy:
      mode: replicated
      replicas: 1