apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: 'n61n3/mail-service:1.0.0'
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          env:
            - name: MAIL_DOMAIN
              value: 'localhost'
            - name: MAIL_HOST
              value: ''
            - name: MAIL_PORT
              value: '1025'
            - name: MAIL_ENCRYPTION
              value: ''
            - name: MAIL_USERNAME
              value: ''
            - name: MAIL_PASSWORD
              value: ''
            - name: FROM_ADDR
              value: 'muyiwa@test.com'
            - name: FROM_NAME
              value: 'Muyiwa Dev'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80
